-- وين دواي؟ - قاعدة البيانات النهائية
create extension if not exists pgcrypto;

create table if not exists public.drugs (
 id uuid primary key default gen_random_uuid(),
 name_ar text not null,
 name_en text,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.pharmacies (
 id uuid primary key default gen_random_uuid(),
 name text not null,
 phone text not null,
 address text,
 area text,
 city text default 'الخرطوم',
 latitude double precision,
 longitude double precision,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.pharmacy_inventory (
 pharmacy_id uuid references public.pharmacies(id) on delete cascade,
 drug_id uuid references public.drugs(id) on delete cascade,
 available boolean not null default false,
 price numeric(12,2),
 next_available_at text,
 updated_at timestamptz not null default now(),
 primary key(pharmacy_id,drug_id)
);

create table if not exists public.availability_requests (
 id uuid primary key default gen_random_uuid(),
 drug_id uuid references public.drugs(id) on delete set null,
 requested_name text not null,
 latitude double precision,
 longitude double precision,
 created_at timestamptz not null default now()
);

create table if not exists public.patient_comments (
 id uuid primary key default gen_random_uuid(),
 comment text not null check(length(comment) between 2 and 2000),
 reply text,
 visible boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
 id bigint generated by default as identity primary key,
 event_type text not null,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
 user_id uuid primary key references auth.users(id) on delete cascade,
 created_at timestamptz not null default now()
);

create table if not exists public.pharmacy_staff (
 user_id uuid primary key references auth.users(id) on delete cascade,
 pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
 created_at timestamptz not null default now()
);

alter table public.drugs enable row level security;
alter table public.pharmacies enable row level security;
alter table public.pharmacy_inventory enable row level security;
alter table public.availability_requests enable row level security;
alter table public.patient_comments enable row level security;
alter table public.analytics_events enable row level security;
alter table public.admin_users enable row level security;
alter table public.pharmacy_staff enable row level security;

-- Public read
drop policy if exists "public read active drugs" on public.drugs;
create policy "public read active drugs" on public.drugs for select using (active=true);

drop policy if exists "public read active pharmacies" on public.pharmacies;
create policy "public read active pharmacies" on public.pharmacies for select using (active=true);

drop policy if exists "public read available inventory" on public.pharmacy_inventory;
create policy "public read available inventory" on public.pharmacy_inventory for select using (available=true);

drop policy if exists "public read visible comments" on public.patient_comments;
create policy "public read visible comments" on public.patient_comments for select using (visible=true);

-- Public inserts needed by the service
drop policy if exists "public register pharmacy" on public.pharmacies;
create policy "public register pharmacy" on public.pharmacies for insert with check (active=true);

drop policy if exists "public add comment" on public.patient_comments;
create policy "public add comment" on public.patient_comments for insert with check (length(comment) between 2 and 2000);

drop policy if exists "public add request" on public.availability_requests;
create policy "public add request" on public.availability_requests for insert with check (length(requested_name) between 2 and 200);

drop policy if exists "public analytics insert" on public.analytics_events;
create policy "public analytics insert" on public.analytics_events for insert with check (length(event_type) between 2 and 80);

-- Authenticated pharmacy staff
drop policy if exists "staff read own pharmacy inventory" on public.pharmacy_inventory;
create policy "staff read own pharmacy inventory" on public.pharmacy_inventory for select to authenticated
using (exists(select 1 from public.pharmacy_staff s where s.user_id=auth.uid() and s.pharmacy_id=pharmacy_inventory.pharmacy_id));

drop policy if exists "staff upsert own pharmacy inventory" on public.pharmacy_inventory;
create policy "staff upsert own pharmacy inventory" on public.pharmacy_inventory for insert to authenticated
with check (exists(select 1 from public.pharmacy_staff s where s.user_id=auth.uid() and s.pharmacy_id=pharmacy_inventory.pharmacy_id));

drop policy if exists "staff update own pharmacy inventory" on public.pharmacy_inventory;
create policy "staff update own pharmacy inventory" on public.pharmacy_inventory for update to authenticated
using (exists(select 1 from public.pharmacy_staff s where s.user_id=auth.uid() and s.pharmacy_id=pharmacy_inventory.pharmacy_id))
with check (exists(select 1 from public.pharmacy_staff s where s.user_id=auth.uid() and s.pharmacy_id=pharmacy_inventory.pharmacy_id));

-- Admin helper
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()) $$;

drop policy if exists "admin read analytics" on public.analytics_events;
create policy "admin read analytics" on public.analytics_events for select to authenticated using (public.is_admin());

drop policy if exists "admin read comments" on public.patient_comments;
create policy "admin read comments" on public.patient_comments for select to authenticated using (public.is_admin());

drop policy if exists "admin update comments" on public.patient_comments;
create policy "admin update comments" on public.patient_comments for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin read pharmacies" on public.pharmacies;
create policy "admin read pharmacies" on public.pharmacies for select to authenticated using (public.is_admin());

-- Seed only the drug catalog, not fake pharmacies.
insert into public.drugs(name_ar,name_en) values
('باراسيتامول','Paracetamol'),
('أموكسيسيلين','Amoxicillin'),
('إيبوبروفين','Ibuprofen'),
('أزيثروميسين','Azithromycin'),
('ميتفورمين','Metformin'),
('أملوديبين','Amlodipine'),
('أوميبرازول','Omeprazole'),
('سيتريزين','Cetirizine')
on conflict do nothing;
